export const LOAD_CHARACTERS_REQUEST = "LOAD_CHARACTERS_REQUEST";
export const LOAD_CHARACTERS_SUCCESS = "LOAD_CHARACTERS_SUCCESS";
export const LOAD_CHARACTERS_FAILURE = "LOAD_CHARACTERS_FAILURE";

export const LOAD_CHARACTERS_BY_COMIC_REQUEST =
  "LOAD_CHARACTERS_BY_COMIC_REQUEST";
export const LOAD_CHARACTERS_BY_COMIC_SUCCESS =
  "LOAD_CHARACTERS_BY_COMIC_SUCCESS";
export const LOAD_CHARACTERS_BY_COMIC_FAILURE =
  "LOAD_CHARACTERS_BY_COMIC_FAILURE";

export const LOAD_CHARACTERS_BY_STORY_REQUEST =
  "LOAD_CHARACTERS_BY_STORY_REQUEST";
export const LOAD_CHARACTERS_BY_STORY_SUCCESS =
  "LOAD_CHARACTERS_BY_STORY_SUCCESS";
export const LOAD_CHARACTERS_BY_STORY_FAILURE =
  "LOAD_CHARACTERS_BY_STORY_FAILURE";

export const LOAD_COMICS_REQUEST = "LOAD_COMICS_REQUEST";
export const LOAD_COMICS_SUCCESS = "LOAD_COMICS_SUCCESS";
export const LOAD_COMICS_FAILURE = "LOAD_COMICS_FAILURE";

export const LOAD_COMIC_BY_ID_REQUEST = "LOAD_COMIC_BY_ID_REQUEST";
export const LOAD_COMIC_BY_ID_SUCCESS = "LOAD_COMIC_BY_ID_SUCCESS";
export const LOAD_COMIC_BY_ID_FAILURE = "LOAD_COMIC_BY_ID_FAILURE";

export const LOAD_CHARACTER_BY_ID_REQUEST = "LOAD_CHARACTER_BY_ID_REQUEST";
export const LOAD_CHARACTER_BY_ID_SUCCESS = "LOAD_CHARACTER_BY_ID_SUCCESS";
export const LOAD_CHARACTER_BY_ID_FAILURE = "LOAD_CHARACTER_BY_ID_FAILURE";

export const LOAD_STORIES_REQUEST = "LOAD_STORIES_REQUEST";
export const LOAD_STORIES_SUCCESS = "LOAD_STORIES_SUCCESS";
export const LOAD_STORIES_FAILURE = "LOAD_STORIES_FAILURE";

export const LOAD_STORY_BY_ID_REQUEST = "LOAD_STORY_BY_ID_REQUEST";
export const LOAD_STORY_BY_ID_SUCCESS = "LOAD_STORY_BY_ID_SUCCESS";
export const LOAD_STORY_BY_ID_FAILURE = "LOAD_STORY_BY_ID_FAILURE";